{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "content-services.shortname" . }}-ooi-service
  labels:
    {{- include "ooi-service.labels" . | nindent 4 }}
  annotations:
    {{- if not (semverCompare ">=1.18-0"  .Capabilities.KubeVersion.GitVersion) -}}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /ooi-service
{{- if .Values.ooiService.extraAnnotations }}
{{ toYaml .Values.ooiService.extraAnnotations | indent 4 }}
{{- end }}

spec:
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: "nginx"
  {{- end }}
  rules:
  {{- if .Values.ooiService.ingress.hostName }}
  - host: {{ tpl .Values.ooiService.ingress.hostName $ }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: {{ .Values.ooiService.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "content-services.shortname" . }}-ooi-service
            port:
              number: {{ .Values.ooiService.service.externalPort }}
      {{- else }}
      - path: {{ .Values.ooiService.ingress.path }}
        {{- if (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
        pathType: Prefix
        {{- end }}
        backend:
          serviceName: {{ template "content-services.shortname" . }}-ooi-service
          servicePort: {{ .Values.ooiService.service.externalPort }}
      {{- end }}
