{{- if .Values.syncservice.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "syncservice.fullname" . }}-ingress
  annotations:
    {{- if not (semverCompare ">=1.18-0"  .Capabilities.KubeVersion.GitVersion) -}}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /alfresco/$2
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "sync_affinity_route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}

spec:
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: "nginx"
  {{- end }}
  rules:
  {{- $hostName := tpl (.Values.ingress.hostName | default "") . }}
  {{- if $hostName }}
  - host: {{ $hostName | quote }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: {{ .Values.syncservice.ingress.path }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ template "syncservice.fullname" . }}
            port:
              number: {{ .Values.syncservice.service.externalPort }}
      {{- else }}
      - path: {{ .Values.syncservice.ingress.path }}(/|$)(.*)
        {{- if (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
        pathType: Prefix
        {{- end }}
        backend:
          serviceName: {{ template "syncservice.fullname" . }}
          servicePort: {{ .Values.syncservice.service.externalPort }}
      {{- end }}
{{- end }}
