{{- if .Values.insightzeppelin.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "alfresco-insight-zeppelin.fullName" . }}
  annotations:
    {{- if not (semverCompare ">=1.18-0"  .Capabilities.KubeVersion.GitVersion) -}}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
spec:
  rules:
  - http:
      paths:
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path:  {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "alfresco-insight-zeppelin.fullName" . }}
            port:
              number: {{ .Values.service.externalPort }}
      {{- else }}
      - path: {{ .Values.ingress.path }}
        {{- if (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
        pathType: Prefix
        {{- end }}
        backend:
          serviceName: {{ template "alfresco-insight-zeppelin.fullName" . }}
          servicePort: {{ .Values.service.externalPort }}
      {{- end }}
{{- end }}
