{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr
  annotations:
    {{- if not (semverCompare ">=1.18-0"  .Capabilities.KubeVersion.GitVersion) -}}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ template "alfresco-search.fullName" . }}-solr
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Alfresco Search Services"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelist_ips }}

spec:
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: "nginx"
  {{- end }}
  rules:
  - http:
      paths:
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "alfresco-search.fullName" . }}-solr
            port:
              number: {{ .Values.service.externalPort }}
      {{- else }}
      - path: {{ .Values.ingress.path }}
        {{- if (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
        pathType: Prefix
        {{- end }}
        backend:
          serviceName: {{ template "alfresco-search.fullName" . }}-solr
          servicePort: {{ .Values.service.externalPort }}
      {{- end }}
{{- end }}
